name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, bioconda
          activate-environment: test

      - name: Install conda packages
        run: |
          conda install bioconda-utils

      - name: Hello World
        run: |
          bioconda-utils --version


