name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge, bioconda
          activate-environment: test
          python-version: "3.10.*"

      - name: Install conda packages
        run: |
          conda list

      # - name: Hello World
      #   run: |
      #     bioconda-utils --version


